### ISSUE TITLE
Label `w0stSKNkKxpbovqC7nMP.png` to `WZVYEUmhIg45sP4ldJVh.png`

### ISSUE THREAD

**Issue by cloudchamb3r** [cloudchamb3r/captcha-ds#18]

**Comment by Kaos599** [comment]
can you assign this to me @cloudchamb3r  i would like to work on this.
Thanks

**Comment by Kaos599** [comment]
hey i have done it with the [PR](https://github.com/cloudchamb3r/captcha-ds/pull/25).

can you please add the label of hacktoberfest to both the issue and the PR before merging?

**Comment by cloudchamb3r** [comment]
Ok
